### ISSUE TITLE
👷 CI/CD 파이프라인 구축

### ISSUE THREAD

**Issue by y2hscmtk** [Hsu-Likelion-12th-Management/rolling-paper#3]
### 🤓 TODO
- [x] AWS 계정 생성
- [x] 네트워크 구축
- [x] RDS 생성
- [x] EC2 생성
- [x] Docker 계정 생성
- [x] CI/CD 파이프라인 구축
 

<br>

### ⏱️ 마감기한
- 12/08
