### ISSUE TITLE
✨롤링페이퍼 홈 API 작성

### ISSUE THREAD

**Issue by y2hscmtk** [Hsu-Likelion-12th-Management/rolling-paper#6]
### 🤓 TODO
- [x] 기본 엔티티 생성 및 연관관계 설정
![image](https://github.com/user-attachments/assets/f7b5baaa-9307-4866-adf1-43e65d08549d)

- [x] 롤링페이퍼 홈 생성 API 작성
- [x] 나의 롤링페이퍼 반환 API 작성

 

<br>

### ⏱️ 마감기한
- 12/13
